import type { StoreProduct } from '@/components/store/types';

export const storeProducts: StoreProduct[] = [
  {
    id: 'demo-product',
    slug: 'daily-comfort-hoodie',
    title: 'Худи Daily Comfort',
    shortDescription: 'Мягкое хлопковое худи.',
    description: 'Мягкое хлопковое худи для повседневного образа.',
    basePriceCents: 4990,
    priceCents: 4990,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Худи',
    imageGradient: 'linear-gradient(135deg, #9fb8ff 0%, #5f7de8 100%)',
  },
  {
    id: 'urban-sneakers',
    slug: 'urban-motion-sneakers',
    title: 'Кроссовки Urban Motion',
    shortDescription: 'Лёгкие кроссовки.',
    description: 'Лёгкие кроссовки с гибкой подошвой.',
    basePriceCents: 7390,
    priceCents: 7390,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Кроссовки',
    imageGradient: 'linear-gradient(135deg, #9ce6d7 0%, #37b59b 100%)',
  },
  {
    id: 'canvas-bag',
    slug: 'canvas-weekend-bag',
    title: 'Сумка Canvas Weekend',
    shortDescription: 'Компактная сумка на каждый день.',
    description: 'Компактная сумка с двумя внутренними карманами.',
    basePriceCents: 3590,
    priceCents: 3590,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Сумка',
    imageGradient: 'linear-gradient(135deg, #f7d8a7 0%, #d6a85b 100%)',
  },
  {
    id: 'smart-bottle',
    slug: 'smart-steel-bottle',
    title: 'Термобутылка Smart Steel',
    shortDescription: 'Термобутылка 500 мл.',
    description: 'Вакуумная термобутылка объёмом 500 мл.',
    basePriceCents: 2490,
    priceCents: 2490,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Бутылка',
    imageGradient: 'linear-gradient(135deg, #b5d3fb 0%, #4d8ddd 100%)',
  },
  {
    id: 'desk-lamp',
    slug: 'focus-desk-lamp',
    title: 'Лампа Focus Desk',
    shortDescription: 'Настольная лампа с тёплым светом.',
    description: 'Настольная лампа с тёплым светом и сенсорным управлением.',
    basePriceCents: 4190,
    priceCents: 4190,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Лампа',
    imageGradient: 'linear-gradient(135deg, #f7e5b9 0%, #d4bb78 100%)',
  },
  {
    id: 'wireless-speaker',
    slug: 'mini-bluetooth-speaker',
    title: 'Колонка Mini Bluetooth',
    shortDescription: 'Компактная портативная колонка.',
    description: 'Карманная колонка с насыщенным низом.',
    basePriceCents: 5890,
    priceCents: 5890,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Колонка',
    imageGradient: 'linear-gradient(135deg, #c2c4fb 0%, #7278e4 100%)',
  },
  {
    id: 'notebook-set',
    slug: 'notebook-set',
    title: 'Набор блокнотов',
    shortDescription: 'Три блокнота в наборе.',
    description: 'Набор из трёх лаконичных блокнотов для заметок на каждый день.',
    basePriceCents: 1390,
    priceCents: 1390,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Блокнот',
    imageGradient: 'linear-gradient(135deg, #f8c8c8 0%, #de7f7f 100%)',
  },
  {
    id: 'charger-kit',
    slug: 'travel-charger-kit',
    title: 'Набор Travel Charger',
    shortDescription: 'Быстрое компактное зарядное устройство.',
    description: 'Быстрая зарядка с компактным дорожным адаптером.',
    basePriceCents: 6790,
    priceCents: 6790,
    compareAtPriceCents: null,
    discountAmountCents: 0,
    appliedDiscount: null,
    currency: 'USD',
    imageLabel: 'Зарядка',
    imageGradient: 'linear-gradient(135deg, #b8ece8 0%, #4ebcb3 100%)',
  },
];

export function findStoreProduct(productId: string): StoreProduct | undefined {
  return storeProducts.find(
    (product) => product.id === productId || product.slug === productId,
  );
}
