import type { StoreProduct } from '@/components/store/types';

export const storeProducts: StoreProduct[] = [
  {
    id: 'demo-product',
    slug: 'daily-comfort-hoodie',
    title: 'Daily Comfort Hoodie',
    shortDescription: 'Soft cotton hoodie.',
    description: 'Soft cotton hoodie for everyday wear.',
    priceCents: 4990,
    currency: 'USD',
    imageLabel: 'Hoodie',
    imageGradient: 'linear-gradient(135deg, #9fb8ff 0%, #5f7de8 100%)',
  },
  {
    id: 'urban-sneakers',
    slug: 'urban-motion-sneakers',
    title: 'Urban Motion Sneakers',
    shortDescription: 'Lightweight sneakers.',
    description: 'Lightweight sneakers with flexible sole.',
    priceCents: 7390,
    currency: 'USD',
    imageLabel: 'Sneakers',
    imageGradient: 'linear-gradient(135deg, #9ce6d7 0%, #37b59b 100%)',
  },
  {
    id: 'canvas-bag',
    slug: 'canvas-weekend-bag',
    title: 'Canvas Weekend Bag',
    shortDescription: 'Compact carry bag.',
    description: 'Compact carry bag with two inner pockets.',
    priceCents: 3590,
    currency: 'USD',
    imageLabel: 'Bag',
    imageGradient: 'linear-gradient(135deg, #f7d8a7 0%, #d6a85b 100%)',
  },
  {
    id: 'smart-bottle',
    slug: 'smart-steel-bottle',
    title: 'Smart Steel Bottle',
    shortDescription: '500 ml insulated bottle.',
    description: 'Vacuum insulated bottle, 500 ml.',
    priceCents: 2490,
    currency: 'USD',
    imageLabel: 'Bottle',
    imageGradient: 'linear-gradient(135deg, #b5d3fb 0%, #4d8ddd 100%)',
  },
  {
    id: 'desk-lamp',
    slug: 'focus-desk-lamp',
    title: 'Focus Desk Lamp',
    shortDescription: 'Warm-white table lamp.',
    description: 'Warm-white table lamp with touch control.',
    priceCents: 4190,
    currency: 'USD',
    imageLabel: 'Lamp',
    imageGradient: 'linear-gradient(135deg, #f7e5b9 0%, #d4bb78 100%)',
  },
  {
    id: 'wireless-speaker',
    slug: 'mini-bluetooth-speaker',
    title: 'Mini Bluetooth Speaker',
    shortDescription: 'Pocket-size speaker.',
    description: 'Pocket-size speaker with rich low end.',
    priceCents: 5890,
    currency: 'USD',
    imageLabel: 'Speaker',
    imageGradient: 'linear-gradient(135deg, #c2c4fb 0%, #7278e4 100%)',
  },
  {
    id: 'notebook-set',
    slug: 'notebook-set',
    title: 'Notebook Set',
    shortDescription: 'Set of 3 notebooks.',
    description: 'Set of 3 minimal notebooks for daily notes.',
    priceCents: 1390,
    currency: 'USD',
    imageLabel: 'Notebook',
    imageGradient: 'linear-gradient(135deg, #f8c8c8 0%, #de7f7f 100%)',
  },
  {
    id: 'charger-kit',
    slug: 'travel-charger-kit',
    title: 'Travel Charger Kit',
    shortDescription: 'Fast compact charger.',
    description: 'Fast charger with compact travel adapter.',
    priceCents: 6790,
    currency: 'USD',
    imageLabel: 'Charger',
    imageGradient: 'linear-gradient(135deg, #b8ece8 0%, #4ebcb3 100%)',
  },
];

export function findStoreProduct(productId: string): StoreProduct | undefined {
  return storeProducts.find(
    (product) => product.id === productId || product.slug === productId,
  );
}
