'use client';

import { useEffect, useRef } from 'react';
import { useRawInitData } from '@tma.js/sdk-react';

function isMockInitData(rawInitData: string): boolean {
  const params = new URLSearchParams(rawInitData);
  return params.get('hash') === 'some-hash';
}

export function TelegramSessionBootstrap() {
  const rawInitData = useRawInitData();
  const attemptedInitData = useRef<string | null>(null);

  useEffect(() => {
    if (!rawInitData) {
      return;
    }

    if (attemptedInitData.current === rawInitData) {
      return;
    }

    // Skip mock data generated by local non-Telegram environment.
    if (isMockInitData(rawInitData)) {
      return;
    }

    attemptedInitData.current = rawInitData;

    void fetch('/api/auth/telegram/bootstrap', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ initDataRaw: rawInitData }),
    }).catch(() => {
      // Session bootstrap failure is non-fatal for read-only storefront mode.
    });
  }, [rawInitData]);

  return null;
}
