'use client';

import { useEffect, useRef } from 'react';
import { useRawInitData } from '@tma.js/sdk-react';

function isMockInitData(rawInitData: string): boolean {
  const params = new URLSearchParams(rawInitData);
  return params.get('hash') === 'some-hash';
}

export function TelegramSessionBootstrap() {
  const rawInitData = useRawInitData();
  const attemptedInitData = useRef<string | null>(null);

  useEffect(() => {
    if (!rawInitData) {
      return;
    }

    if (attemptedInitData.current === rawInitData) {
      return;
    }

    // Skip mock data generated by local non-Telegram environment.
    if (isMockInitData(rawInitData)) {
      return;
    }

    attemptedInitData.current = rawInitData;

    void (async () => {
      try {
        const response = await fetch('/api/auth/telegram/bootstrap', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
          body: JSON.stringify({ initDataRaw: rawInitData }),
        });

        if (!response.ok && process.env.NODE_ENV === 'development') {
          const payload = (await response.json().catch(() => null)) as
            | { error?: string; details?: string[] }
            | null;
          console.warn(
            '[MainStore] Telegram session bootstrap failed',
            payload?.error ?? `HTTP ${response.status}`,
            payload?.details ?? [],
          );
        }
      } catch {
        // Session bootstrap failure is non-fatal for read-only storefront mode.
      }
    })();
  }, [rawInitData]);

  return null;
}
